test for arg

diff --git a/bin/ori-pull b/bin/ori-pull
--- a/bin/ori-pull
+++ b/bin/ori-pull
@@ -6,5 +6,9 @@ if ! which ori >/dev/null 2>&1 ; then
     echo "ERROR: ori not found."
     exit 1
 fi
+if [ "x" = "x${FSNAME}" ]; then
+    echo "ERROR: 1 arg required."
+    exit 1
+fi
 
 ori pull ${FSNAME}
diff --git a/bin/orifs-mount b/bin/orifs-mount
--- a/bin/orifs-mount
+++ b/bin/orifs-mount
@@ -7,5 +7,9 @@ if ! which orifs >/dev/null 2>&1 ; then
     echo "ERROR: orifs not found."
     exit 1
 fi
+if [ "x" = "x${MNTPOINT}" ]; then
+    echo "ERROR: 2 args required."
+    exit 1
+fi
 
 orifs --repo=${FSNAME} ${MNTPOINT}
diff --git a/bin/orisync-init b/bin/orisync-init
--- a/bin/orisync-init
+++ b/bin/orisync-init
@@ -6,6 +6,10 @@ if ! which orisync >/dev/null 2>&1 ; then
     echo "ERROR: orisync not found."
     exit 1
 fi
+if [ "x" = "x${FSNAME}" ]; then
+    echo "ERROR: 1 arg required."
+    exit 1
+fi
 
 orisync init
 orisync add ${FSNAME}
